### PR TITLE
Fixed Navbar and products close button

### PR DESCRIPTION
**Pull request by soujanyaj11**
The Navbar bookmarks are fixed with appropriate links.
The pop up box on read more products page is now closing correctly.

### CODE REVIEW

**Comment by enoueni** [comment]
yea thanks soujanya...it looks better

**Comment by enoueni** [comment]
so, I can see the one Ola did the pop up is still there...and it's not going back when you go hover the read more...

**Comment by soujanyaj11** [comment]
> so, I can see the one Ola did the pop up is still there...and it's not going back when you go hover the read more...

Hi Team, Can you review the following changes below,
1)Fixed the order of the navbar to reflect the section order on the website. 
2) Added About us section to the nav bar.

**Comment by webxacademy** [comment]
> > so, I can see the one Ola did the pop up is still there...and it's not going back when you go hover the read more...
> 
> Hi Team, Can you review the following changes below, 1)Fixed the order of the navbar to reflect the section order on the website. 2) Added About us section to the nav bar.

Great job!

**Comment by webxacademy** [comment]
There was a conflict but it has been manually resolved and your codes are merged.. Thanks

**Pull request merged**
