### PR TITLE
Landing page, header, Navigation, service/product section

### LINKED ISSUE #17: fix issues for
oioiwqopwqopwal;al;wal..

### LINKED ISSUE #18: Landing page video cover
Make the landing page background video cover the entire page and center responsively.

### PR DESCRIPTION
**Pull request by mkamiw**
We created the landing page with video background with toggle nav bar and service/product sections.

### CODE REVIEW

**Comment by electricpluton** [comment]
Home page look little bit weird on our browser
lotus

**Comment by soujanyaj11** [comment]
> Home page look little bit weird on our browser lotus

image
This issues has been fixed

**Comment by soujanyaj11** [comment]
@electricpluton @JustusDavis @enoueni . Our team has fixed the background issues and make some changes in the CSS. Team A please review the changes and merge if satisfied.

image

**Comment by enoueni** [comment]
Thanks Team C for fixing the issues.  Everything looks good. I will go ahead at merge this to master branch.

**Pull request merged**
