### PR TITLE
About us 

### PR DESCRIPTION
**Pull request by mkamiw**
Created about us section. Added html and css and owner's image folder with images.

### CODE REVIEW

**Comment by enoueni** [comment]
ok we are checking.....

**Comment by enoueni** [comment]
we feel like the picture is too big and we'd like to see the full image instead of seeing half-half

**Comment by enoueni** [comment]
Also, the owners have the same name?

**Comment by soujanyaj11** [comment]
We are working on it.

**Comment by soujanyaj11** [comment]
> Also, the owners have the same name?

We fixed the issues, let us know if there is anything else.

**Comment by JustusDavis** [comment]
That is all. Thanks.

**Pull request merged**
