### PR TITLE
Added Gallery Section

### LINKED ISSUE #22: Add comments to the Gallery HTML
The Gallery Html needs comments

### PR DESCRIPTION
**Pull request by digitalehnds**
Added the HTML/CSS code for the gallery

### CODE REVIEW

**Comment by enoueni** [comment]
Can you please add a comment to your HTML code?

**Comment by digitalehnds** [comment]
> Can you please add a comment to your HTML code?

Sure.

**Comment by digitalehnds** [comment]
Comments fixed

**Comment by enoueni** [comment]
Thanks guys we are all set.

**Pull request merged**
