### PR TITLE
Team Section

### PR DESCRIPTION
**Pull request by enoueni**
1. Added HTML and CSS code for the team section

2. Added Images for the team members

3. Added and style the social media links for each team member

### CODE REVIEW

**Comment by enoueni** [comment]
Team C . Please kindly take a look at our pull request and let us know is there is anything that need to be fixed..

**Comment by soujanyaj11** [comment]
I'm seeing the image sizes are different for each team member. Can that be fixed?

**Comment by enoueni** [comment]
> I'm seeing the image sizes are different for each team member. Can that be fixed?

These are the original images available on the lotus website at the moment. We will need to request a better image from them. Otherwise, this is what we are left with except you want us to replace them with a temporary image.

**Comment by soujanyaj11** [comment]
Understandable. We can keep same images for now.

**Comment by enoueni** [comment]
> Understandable. We can keep same images for now.

ok

**Comment by mississippi662** [comment]
hi

**Comment by soujanyaj11** [comment]
We reviewed the code, everything looks good.

**Pull request merged**
